#! /usr/bin/env bash
#set -euo pipefail
. include "args"
# Public API
# file.is.present $file_name
# file.is.absent $file_name
# file.has.perms $perms $file_name
# file.has.owner $owner:group $filename
# file.assert.size $size $file_name

function tar.is.extracted() {
  args.assert.double "$@"
  local SOURCE="$1"
  local DEST="$2"
  tar xf "$SOURCE" -C "$DEST"
}
