#! /usr/bin/env bash
#set -euo pipefail
. include "args"
# Public API
# apt.installed pkg [pkg...]
# apt.removed pkg [pkg...]

function apt.assert.exists() {
  args.assert.single "$@"
  if [[ $(apt-cache showpkg "$1" | wc -l) -lt 2 ]]; then
    # Really? Let's refresh and make sure
    apt.cache.update force
    if [[ $(apt-cache showpkg "$1" | wc -l) -lt 2 ]]; then
      return 2
    fi
  fi
}
function apt.assert.installed() {
  args.assert.single  "$@"
  result=($(dpkg-query --status "$1" 2>/dev/null | grep -w "^Status:" ))
  if ! [[ ${#result[@]} -ge 2 && ${result[1]} == "install" ]]; then
    return 2
  fi
}
function apt.assert.removed() {
  ! apt.assert.installed "$@"
}


function apt.what_provides() { # Useful but not sure what to do with it
  args.assert.single "$@"
  file=$(which "$1")
  dpkg -S "$file" | sed 's/:.*$//'
}
function apt.cache.assert.stale() { # uses a TTL of 24 hours
  return $(( $(date +%s) - $(stat -c %Y /var/cache/apt) < 24*60*60 ))
}
function apt.cache.update() {
  if apt.cache.assert.stale || [[ "$#" -ne 0 ]] && [[ "$1" == "force" ]]; then
    sudo apt-key update           # Update signing keys (to prevent errors)
    sudo apt-get update           # Update package cache
  fi
}
function apt.cache.clean() {
  sudo apt-get clean -y         # Empty the package cache to save disk space.
}
function apt.upgrade_all() {
  apt.cache.update
  sudo apt-get dist-upgrade -y  # Ensure all packages are at the latest version.
                                # dist-upgrade may remove packages to resolve conflicts but that's OK here
  sudo apt-get autoremove -y    # Remove old packages no longer needed
  sudo apt-get autoclean -y     # Remove deprecated archives from the package cache
}
function apt._install() {
  args.assert.single "$@"
  local PACKAGE="$1"
  # If an error is encountered during installation...
  if ! (set -x; apt-get install -y "$PACKAGE") ; then
    # Update keys and cache and retry
    apt.cache.update force
    (set -x; apt-get install -y "$PACKAGE")
  fi
  apt.assert.installed "$PACKAGE"
}
function apt._missing_packages() {
  packages=()
  for PACKAGE in "$@" ; do
    if apt.assert.exists "$PACKAGE" ; then
      if ! apt.assert.installed "$PACKAGE" ; then
        echo "$PACKAGE"
      fi
    else
      >&2 echo "Package '$1' does not exist (according to apt-cache search)"
      return 1
    fi
  done
}

function apt.is.installed() {
  if packages=$(apt._missing_packages "$@") ; then
    for PACKAGE in $packages ; do
      apt._install "$PACKAGE"
    done
  fi
}
function apt.is.removed() {
  for PACKAGE in "$@"; do
    if apt.assert.installed "$PACKAGE" ; then
      sudo apt-get remove -y $package
      apt.assert.removed "$PACKAGE"
    fi
  done
}
function apt.unattended-upgrades.is.enabled() {
  apt.is.installed unattended-upgrades
  echo 'unattended-upgrades unattended-upgrades/enable_auto_updates boolean true' | sudo debconf-set-selections
  sudo dpkg-reconfigure unattended-upgrades -f noninteractive
}
function apt.unattended-upgrades.is.disabled() {
  if apt.assert.installed unattended-upgrades
  then
    echo 'unattended-upgrades unattended-upgrades/enable_auto_updates boolean false' | sudo debconf-set-selections
    sudo dpkg-reconfigure unattended-upgrades -f noninteractive
  fi
  apt.is.removed unattended-upgrades
}
