#! /usr/bin/env bash
#set -euo pipefail
. include "args" "dir"
# Public API

function tar.is.extracted() {
  args.assert.double "$@"
  local SOURCE="$1"
  local DEST="$2"
  dir.is.present "$DEST"
  tar xf "$SOURCE" -C "$DEST"
}
