#! /usr/bin/env bash
#set -euo pipefail
. include "args"
# Public API

function zip.is.extracted() {
  args.assert.double "$@"
  local SOURCE="$1"
  local DEST="$2"
  dir.is.present "$DEST"
  (set -x; unzip -uo "$SOURCE" -d "$DEST")
}
